// core/src/index.ts
export * from './types'
export * from './charsets'
export { createCanvasGlyphMeasurer } from './glyphMeasure'
export { buildFontWidthTable } from './fontWidthTable'
export { computeDownscaleDimensions } from './downscale'
export { decodeAndPrepareImage } from './ingest'
export { computeBlockLuminance, mapLuminanceToChar } from './mapping'
export { assembleGrid } from './grid'
export { renderGridToCanvas, type RenderOptions, type RenderResult } from './renderGridToCanvas'
export { toText } from './export/toText'
export { toXHTML, type XHTMLOptions } from './export/toXHTML'
export { toRTF } from './export/toRTF'
export { toImage, type CanvasLike, type CanvasFactory } from './export/toImage'
